# Generated by Django 2.2 on 2020-07-26 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['status'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['status'], 'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-publish'], 'verbose_name': 'آزمون', 'verbose_name_plural': 'آزمون ها'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_four',
            field=models.CharField(max_length=200, verbose_name='گزینه چهار'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_one',
            field=models.CharField(max_length=200, verbose_name='گزینه یک'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_three',
            field=models.CharField(max_length=200, verbose_name='گزینه سه'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_true',
            field=models.IntegerField(choices=[(1, 'یک'), (2, 'دو'), (3, 'سه'), (4, 'چهار')], verbose_name='گزینه صحیح'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_two',
            field=models.CharField(max_length=200, verbose_name='گزینه دو'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(related_name='question', to='exam.Quiz', verbose_name='آموزن'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('p', 'منتشر شده'), ('d', 'پیشنویس')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ManyToManyField(related_name='quiz', to='exam.Category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
