# Generated by Django 2.2.13 on 2020-07-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20200729_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_four',
            field=models.CharField(max_length=300, verbose_name='گزینه چهار'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_one',
            field=models.CharField(max_length=300, verbose_name='گزینه یک'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_three',
            field=models.CharField(max_length=300, verbose_name='گزینه سه'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_two',
            field=models.CharField(max_length=300, verbose_name='گزینه دو'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان'),
        ),
    ]
